import type { NextPage } from 'next'
import Head from 'next/head'
import HomeContainer from "../containers/index";

const Home: NextPage = () => {
  return (
    <div className="py-9">
      <Head>
        <title>Pokémon Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/1068/1068780.png" />
      </Head>
      <HomeContainer/>
    </div>
  )
}

export default Home
