import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import ButtonFromProps from './button'

const Home: NextPage = () => {
  const [data, setData] = useState({name: '', avatar: ''});
  const url = 'https://pokeapi.co/api/v2/pokemon/';
  const randomNum = Math.floor(Math.random() * 898 ) + 1;

  const fetchPokemon = async () => {
    fetch(url+randomNum)
    .then((res) => {
      if (res.status == 200) return res.json();
    })
    .then((res) => {
      setData({...data, name: res.forms[0].name, avatar: res.sprites.front_default})
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokémon Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/1068/1068780.png" />
      </Head>

      <main className={styles.main}>
        {data.name != '' && <div>
          <p className={styles.title}>Gotcha!<br />You caught <b>{data.name}</b></p>
          <img src={data.avatar} alt={data.name} className={styles.image} />
          </div>}

        <ButtonFromProps text='Catch a Pokémon' onClick={fetchPokemon}></ButtonFromProps>
      </main>
    </div>
  )
}

export default Home
